#!/bin/sh -e

if [ -n "$CONFIG" ]
then
    echo '^!?ilm\??$'
    exit 0
fi

__get() {
    c="/tmp/ilm-cache-$( echo "$1" | md5sum | awk '{print $1}' )"
    [ -f "$c" ] && a=$(( $( date +%s ) - $( date -r "$c" +%s ) ))
    if [ ! -f "$c" ] || [ "$a" -gt 500 ]
    then curl -s -A tiny-matrix-bot -o "$c" "$1"
    fi
    cat "$c"
}

__ilmateenistus() {
    __get http://www.ilmateenistus.ee/ilma_andmed/xml/observations.php \
        | xmlstarlet sel -t -v "/observations/station[name='$1']/airtemperature"
}

__print() {
    printf '%s: %.1f °C\n' "$1" "$2" \
        | sed 's/\./,/' \
        | sed 's/,0//'
}

__print Tallinn "$( __ilmateenistus Tallinn-Harku )"

__print Tartu "$( __ilmateenistus Tartu-Kvissental )"

__print Pärnu "$( __ilmateenistus Pärnu )"

__print Võru "$( __ilmateenistus Võru )"

__print Elva "$( __ilmateenistus Elva )"
