#!/bin/sh -e

if [ -n "$CONFIG" ]
then
    echo '^!?ilm\??\s*$'
    exit 0
fi

for cmd in curl xmlstarlet
do
    if ! command -v "$cmd" > /dev/null
    then
        echo "$cmd: command not found"
        exit 0
    fi
done

__curl() {
    cache="/tmp/ilm-cache-$( echo "$1" | md5sum | awk '{print $1}' )"

    age=0

    if [ -f "$cache" ]
    then
        age=$(( $( date +%s ) - $( date -r "$cache" +%s ) ))
    fi

    if [ ! -f "$cache" ] || [ "$age" -gt 300 ]
    then
        if result="$( curl -sSL -A tiny-matrix-bot "$1" )"
        then
            echo "$result" > "$cache"
        fi
    fi

    cat "$cache"
}

__ilmateenistus() {
    __curl https://www.ilmateenistus.ee/ilma_andmed/xml/observations.php \
        | sed 's/[õä]/x/' \
        | xmlstarlet sel -t -v \
            "/observations/station[name='$1']/airtemperature"
}

__print() {
    printf '%s: %.1f °C\n' "$1" "$2" \
        | sed 's/\./,/' \
        | sed 's/,0//'
}

__print 'Tallinn' "$( __ilmateenistus 'Tallinn-Harku' )"

__print 'Tartu' "$( __ilmateenistus 'Tartu-Kvissental' )"

__print 'Pärnu' "$( __ilmateenistus 'Pxrnu' )"

__print 'Võru' "$( __ilmateenistus 'Vxru' )"

__print 'Elva' "$( __ilmateenistus 'Elva' )"
