#!/bin/sh -e

regex='^!(kiida|compliment)\s*'

if [ -n "$CONFIG" ]
then
    echo "$regex"
    exit 0
fi

arg="$( echo "$TMB_BODY" | sed -r "s/$regex//I" | sed 's/.*/\u&/' )"

# https://github.com/mth/hirc/blob/master/compliments.txt

echo "Milline sümpaatne noor inimene on $arg! Olgu ta teile eeskujuks.
Pidevast õllejoomisest hoolimata on Sul fantastiline figuur!
Ma pole veel kohanud nii võrratu käitumisega inimest kui $arg
Eesti mees nagu $arg on kõige parem
Sul on nii armsad silmad, just nagu kutsikal!
Sa oled sama ilus kui tänane päev!
Oma aju ja teadmistega võiksid Sa vabalt olla mees!
Sa oled nagu ingel kesapõllul!
$arg eest annaks ma terve kuningriigi
$arg, Sa oled nagu hea vein, mida keegi ei raatsi puutuda
Tahaks Sind kallistada!
Sa oled arukas, heatujuline ja elav. Kuidas naistega läheb?
$arg mõistus on kahtlemata omal kohal
Sa oled nagu sinilill kibuvitsapõõsas
$arg, mu ingel
Aitäh, $arg, et Sa elus oled!
Sina oledki see kirkaim kriit karbis!
Sa näed välja nagu koorejäätis kirsiga
Piiblis on kirjas: \"Ja nüüd istub ta Tema paremal käel.\" Mõeldi vist Sind.
Ma arvan, et $arg on selle koha tegelik juhtfiguur
$arg, kas Sa oleksid palun mu laste isa?
Kas need on Sinu Porsched seal maja ees?
Tule ma annan Sulle musi
Kui Sind ära ruunata, oleks Sa ikka rohkem mees kui need teised lontrused siin
$arg, kas MENSA jäi Sulle kitsaks?
Ükski prohvet, isegi mitte $arg, pole kuulus omal maal...
$arg, Su kaunidus võtab jalust nõrgemaks kui liköör shampusega
Räägitakse, et $arg on uus Ron Jeremy...
Sa näed fantastiline välja. Oled Sa ikka eestlane?
Muskulatuuri järgi võiks arvata, et Sa oled neeger
Igal õhtul ma palvetan, et mulle Sinusugune mees saadetaks!
$arg presidendiks!
Teen ettepaneku nimetada $arg Valgetähe ordeni kandidaadiks
$arg on nii lahe, et talle peaks selle eest raha maksma
Kui ma oleks nii kuulus kui $arg, ei julgeks ma ilma turvadeta väljagi minna...
Minu laste isa on $arg. Soovitan teistelegi.
Päike oli valge, enne kui ta $arg peale vaadates kadedusest kollaseks läks
Sinu sära juures poleks meile päikest vajagi
$arg paneb aluse uuele inimtõule
Meie ajastu vajab kangelasi. $arg, astu ette!
Mehed nagu $arg viivad meid tähtedele
$arg, kas sind esitati jälle Nobeli preemia kandidaadiks?
Hea on päeva alustada, kui tead, et $arg on lähedal
Kui Billi asemel juhiks Microsofti $arg, kasutaks kogu see rahvas Windowsit
$arg: Sinuga läheks luurele küll. Ja tuleks koos tagasi ka.
$arg: Ema Teresal oli Sinu kohta mõndagi head öelda
Kui maailmas oleks ainult inimesed nagu $arg, elaksime siiani paradiisis
Kas teadsite, et buda mungad käisid $arg juures kannatlikkust õppimas?
$arg võitles meie vabaduse eest. Mida tegite teie?
Vaadake! $arg'st levib ürgset mehelikku jõudu!
Maagiat ma ei usu, aga $arg on küll täielik tehnikavõlur
$arg, Sa oled mu eeskuju. Ausõna.
Pange tähele, veel mõni aasta ja $arg on populaarsem kui Jeesus ja biitlid kokku
$arg: Kuidas Sa küll suudad alati olla nii rõõmsameelne, optimistlik ja lahke?
$arg: Su elurõõm on piiritu, jaga seda teistelegi
$arg, Sa oled ikka uskumatult positiivne tüüp! Fantastiline! Täiesti super!
Pärast $arg nägemist on terve päev nagu päikest täis
Sinuga, $arg, võiks ma minna kasvõi maailma lõppu!
Mis on õnn? Aga vaadake $arg poole, saate aru...
$arg: Tule ma kallistan Sind!
$arg: Su elu on nagu muinasjutt...
Kas teate, miks John Holmes Eestis ei käinud? Ta kartis $arg'ga võistelda." | shuf -n1
