#!/bin/sh -e

regex='^!(otsusta|vali|decide|pick)\s*'

if [ -n "$CONFIG" ]
then
    echo "$regex"
    exit 0
fi

arg="$( echo "$TMB_BODY" | sed -r "s/$regex//I" )"

if [ -z "$arg" ]
then
    exit 1
fi

printf 'hmm...\n\n%s\n' \
    "$( echo "$arg" | sed -r 's/(\s+(ja|või|and|or)\s+)/\n/gI' | shuf -n1 )"
