#!/bin/sh -e

regex='^!pla+n\s*'

if [ -n "$CONFIG" ]
then
    echo "$regex"
    exit 0
fi

arg="$( echo "$TMB_BODY" | sed -r "s/$regex//I" )"

if [ -z "$arg" ]
then
    exit 1
fi

# https://github.com/mth/hirc/blob/master/plans.txt

printf '1. %s\n\n2. ???\n\n3. %s\n' \
    "$arg" \
    "$( echo "[CENSORED]
[CLASSIFIED]
kõik perses
valus perse
valus munn
make profit
räige kasum
sitaks õlut
rule the world
ilus elu
lihtne elu
lihtsalt masendav
ulmeline aldaris
nõukogude võim
kerge joove
raske joove
erakorralised valimised
tagasi paastu ja palve juurde
sittagi pole muutunud
erakordselt sitt pohmakas
metsas läheb elu käima
naabrimutt saab infarkti
tehnoloogiasektor langeb kolinal
kõigil on savi
maapealne paradiis
uuele katsele
juhtum antakse kaitsepolitseile uurida
nobeli preemia
spot the loony!
kesknädalas ilmub pisike nupuke toimunu kohta
mõistus kirjutab lahkumisavalduse
mõistus läheb puhkusele
peaks vist advokaadi palkama
Kroonikal on jälle millest kirjutada
tekib röögatu hunnik tagantjärele tarkust
erakordselt külm talv
maakera jääb häbi pärast seisma
kast viina kõigile
viina defitsiit
poest saab lauaviin otsa
igale pensionärile tasuta suitsuvorst
saabub 1000 aastane rahuriik
Eesti saab uue peaministri nõuniku
sotsiaalministeeriumil valmib esimene edukas e-lahendus
tühistatakse viimane rahareform
Tapa Edasi hakkab uuesti ilmuma
lihtsalt sitt
massirepressioonid
puhas nauding
nädalane orgia
ilge porno
kristlikud organisatsioonid avaldavad hukkamõistu
Venemaa avaldab hukkamõistu
rahvusvaheline tunnustus ja tohutu edu!
valitsus tellib Lätist veekahuri
kogu raha on maha joodud
rootsi kardinad
Katrin Lust-Buchanan kirjutab Delfisse uue nutuloo
sa näed telepurgist hommikust Haloneni
100k preemiat ja õhtulehe esikaas
Halonen toob kohvikõrvaseks põhjapõdraspermat
suurenenud teotahe
sama jama, uus nimi
lõõgastav õhtu fooliummütsiga mullivannis
üleestiline reede
hea pidu
halb pidu
PÕMM!
kuskil on piir" | shuf -n1 )"
