#!/bin/sh -e

regex='^\!(solva|insult)\s*'

if [ -n "$CONFIG" ]
then
    echo "$regex"
    exit 0
fi

arg="$( echo "$TMB_BODY" | sed -r "s/$regex//I" )"

# https://github.com/mth/hirc/blob/master/insult.txt

echo "$arg: sa oled nuhtluseks maailmale loodud, et inimesed näeksid, kui madalale võib üks inimeseloom langeda.
$arg: sa oled loll nagu lauajalg.
Tead $arg, mine osta õige üks tükk seepi.
Erikuradikinomees sa $arg oled, reede õhta maatriksis!
$arg: sa oled üks plekist persega vedruvasikas.
$arg: käi jala.
$arg, sa vana pede, sinu kohta on artikkel: http://www.$arg.isgay.com/
$arg: kalla end piimaga üle ja pane traktori kõrval põlema.
Oh püha perse kiriku laes, kuskohas küll $arg'suguseid produtseeritakse.
$arg: sina mine perse ja jäägi sinna.
$arg: vabanda, kui ma sind kuidagi solvasin. See juhtus täiesti tahtlikult.
$arg: ma ei saa aru, kuidas päike küll sinu peale paistes oksendama ei hakka.
$arg: tra küll, kui mina sinu moodi välja näeks, ei julgeks ma ilma maskita väljagi minna
$arg: ma ei näe su silmis mõistusehelki.
$arg: kes küll sinusugusele ajukääbikule kirjakunsti õpetas?
$arg: sina, sitavikat, ime kella!
$arg: kas see on su nina, või kasvatad endale kolmandat kätt?
$arg: mina olen blond, aga mis sinu vabandus on?
$arg: kuidas Sulle kõrvaltvaatajana inimsugu tundub?
$arg: sina ja inetu? Sa ei ole inetu, sa oled lihtsalt ... äh kuradile, Sa oled inetu. Sitaks inetu. Ja paks ka. Ja kiilakas.
$arg: mitu korda ma pean vett tõmbama, et sa ära kaoksid?
$arg: oled sa alati nii loll või on sul lihtsalt blond hetk??
K: Mida ütles jumal, kui ta $arg' tegi? V: Oh shit!
K: Kui Empire State Building'u katuselt kukuvad alla paks neeger ja $arg, siis kumb jõuab alla esimesena? V: Pole valge mehe asi.
K: Mis on $arg' jaoks pikk ja raske? V: Algkool
$arg pole just karbi kõige kirkam kriit
$arg: sa oled erakordselt sita väljanägemisega. On see mingi uus trend?
$arg: kumb meist nüüd mürki peaks võtma?
$arg: mõni küla on sinu pärast praegu ilma lollita.
$arg: on see kitsehabe või on tuvid su lõua täis sittunud?
$arg: palun seisa allatuult.
$arg: sae pekki.
$arg: Ah keri pekki
Kuule $arg, sina kõdunenud kammeljas, sina mädanenud mudakukk, sina solgitud särg, mine osta omale õng.
$arg: näri muru!
$arg: kes sinusugusele kulendile suu andis?
$arg: tead mis, PANE ENNAST PÕLEMA!
$arg: söö sitta! (miljardid kärbsed ei saa ju ometi valel teel olla)
$arg: sa näed välja nagu keedetud kaheksajalg
$arg: sa oled meditsiiniline ime
$arg: sa näed ikka vahva välja! See kleit su seljas on pilapoest, eks?
$arg: kao eemale! Sa seisad mu aura peal!
$arg on mees, kes ei tee palju sõnu. Aga möliseb ikkagi rohkem kui vaja.
. o O ( Kus on geenipolitsei? Siin on mingi jälk $arg ) O o .
. o O ( Millise kivi alt küll sellised lontrused nagu $arg välja ronivad.. ) O o .
$arg: kes ma Sinu arust olen? Kärbsepaber idiootidele?
$arg: on Sul minut aega? Räägi mulle ära kõik, mida Sa üldse tead.
$arg on nii loll, et sobiks ideaalselt Võrno saatesse
$arg: Su jutt kõlab nagu eesti keel, aga ma ei saa mitte halligi aru.
$arg: kõik mu eelarvamused Sinu suhtes on ajapikku tõeks osutunud.
$arg: ilmselgelt on ainuke lahendus sinu probleemile suitsiid.
$arg: see et keegi sind ei mõista, ei tähenda veel et oled kunstnik.
$arg varub ilmselt alati spetsiaalselt aega, et end avalikus kohas lolliks teha.
$arg: Kuuldavasti oli sul kunagi yks mõte, aga see suri yksinduse kätte ära.
$arg: Ma vihkan kõiki. Sina oled järgmine.
$arg: Ja sinu täiesti mõttetu arvamus on...?
$arg: Pista pea perse ja tee porgandi häält.
$arg: Kas sa nüüd taipad, mis juhtub kui sugulased omavahel abielluvad?
$arg: Maakeral ei ole enam ruumi. Mine koju.
$arg: Mine hoia oma pead vee all.
Isegi lollide maailmameistrivõistlustel saaks $arg teise koha, kuna ta on lihtsalt niivõrd loll....
$arg: mine ära enne kui ma sind ümber lükkan.
Näe, tõmbasin küll vett, aga $arg ikka alla ei läinud.
Miskit rõvedat pininat tuleb kusagilt. Aaa, see oled sina, $arg!
Tere $arg! Kuidas viinaravi edeneb?
Vaene $arg, kas sa jäid rongi alla või oledki sellisena sündinud?
$arg: Piiblis on kirjas: \"Juudas eemaldus ja läks ja poos end üles.\" Ja veel: \"Mine tee sina samuti\"
$arg, miks sa ei lase oma mõistust teritada?
$arg, tee mulle üks teene - ära unusta koduteel vales kohas tänavat ületada.
$arg, mängime kodu, Sina oled uks ja mina löön su kinni.
$arg, lähme kusagile, kus me saaksime teineteisest lahus olla.
Ma ei unusta kunagi ühtegi nägu, aga $arg puhul olen ma valmis erandi tegema.
$arg, vaata, rong läheneb! Roni rööbastele!
$arg, Sul on väga huvitav nägu, mitu korda Sind sinna löödud on?
$arg, mängime hobust. Mina olen esimene ots ja sina võid lihtsalt iseennast mängida.
$arg nalju tervitab alati suur vaikusepahvak.
Ahv heitis $arg'le ühe pilgu ning karjus: \"Persse see Darwini teooria - mina endast inimest teha ei lase!\"
Peab tunnistama, et $arg'i sugused mehed ei kasva puu otsas - nad ripuvad okste küljes.
Kas tõesti on sõnade helge pea ja $arg vahel nii suur erinevus?
$arg on nagu lauaga löödud. Ja mitte ainult vastu rindu
Vaata $arg't. Ilmne tõestus, et hullari aed on liiga madal.
Mõistuse pooles on $arg'le kõige lähemal reha ... või äärmisel juhul labidas
$arg, kas sa nüüd taipad, mis juhtub, kui sugulased omavahel abielluvad?
$arg, ma suudan vaevu oma ükskõiksust vaos hoida
$arg, sa tuled tuttav ette. Lahkasin sind vist zooloogiatunnis?
Kui mind huvitaks su arvamus, $arg, siis ütleksin, milline see on.
Sinuga dringile, $arg? Pigem teen endale ise tuimestuseta pimesooleoperatsiooni.
$arg, kas sulle tundub, et ma vajan seltskonda?
Hei, sina, $arg! Kao mu planeedilt minema!
$arg, ja sinu tattnina-arvamus on...?
$arg, ma ei ole tige. Olen lihtsalt juba 10 aastat väga halvas tujus.
$arg, mis stiilis sa ka riietuda ei üritanud, välja see sul igastahes ei tulnud.
$arg, kas su koduplaneedil keegi kunagi vait ka on?
Ma ei ole sinu tüüp, $arg. Ma pole täispuhutav.
$arg, kao eemale! Sa seisad mu aura peal.
$arg: Ära muretse. Ma ei mäleta sinu nime ka.
$arg, ma tahan lihtsalt kätte maksta. Mis selles halba on?
$arg, kummarda ja ütle: \"Jah, mu käskija.\"
$arg, kas ma mainisin, et kui sa minuga räägid, saad kohe jalaga munadesse?
$arg, sa näed erakordselt sitt välja. On see mingi uus trend?
$arg, kumb meist nüüd rohtu peaks võtma?
$arg: Kuidas seda laserkaardikeppi taparežiimile lülitatakse?
Ja milline seitsmest pöialpoisist sina, $arg, oled?
$arg: Ma sorisin küll kaltsupoes, aga seda hilpu ma seal küll ei näinud
Kus on geenipolitsei? Siin on mingi mutant, kes kasutab nime $arg.
$arg, küll sa näed ikka vahva välja. See kleit on sul pilapoest, eks?
$arg, muidugi on ka meestel tunded. Aga keda see kotib?
Ilus kleit, $arg. Loodad alla võtta, et sellesse ära mahtuda?
Parem ära mind vihasta $arg. Mul hakkavad kirstud otsa saama
Oi, kui kena raseda kleit $arg. Sa polegi? Nojah ...
Ma ei usu imesid, $arg. Ma arvestan nendega
$arg, räägi siis ometi! Sul on õigus oma lollile arvamusele.
Ma vihkan kõiki. Sina, $arg, oled järgmine.
$arg, Ja sinu täiesti mõttetu arvamus on...?
$arg: Vaata ette - mul on oma arvamus ja ma tean, kuidas seda kasutada.
$arg: Miks kipuvad kinniste peadega inimesed alati suu lahti tegema?
Ma olen andekas mitmel alal, $arg. Suudan ühteaegu rääkida ja sinu peale laias kaarest kusta.
Ära hakka minuga plõksima, $arg. Nagunii sa jagu ei saa.
Kuidas ma saangi sinust puudust tunda $arg, kui sa kuidagi ära ei lähe?
$arg: Stress kasvab üle pea, aga kägistada pole kedagi.
$arg, sina oled üks hirmus õnnetus, mis headele inimestele kaela kukub.
$arg, Sul on õigus vaikida. Kasuta seda ometi!
Kui inimest toiduga võrrelda, siis sina, $arg, oled odav, maitsetu ja saad kiiresti valmis.
$arg, kuuldavasti oli sul kunagi üks mõte, aga see suri üksinduse kätte ära.
$arg, inetusvõistlusel oleks sulle vääriliseks vastaseks ainlt üleeilne okseloik.
$arg: Ma olen nii õnnelik, et võiksin tappa.
$arg, vabanda, kui tundus, et huvitad mind. Ei huvita.
$arg, su tänane meik on küll puhas raiskamine.
$arg, ma pole sinu tüüp. Mul on pulss.
$arg, ma ei tea, mis viga sul küljes on, aga kindlasti on see raskesti hääldatava diagnoosiga.
$arg, mida ma küll sinuta pihta hakkaksin? Peale selle, et oleksin õnnelik.
Palun räägi edasi, $arg. Ma tahan magada.
$arg, jah, see on noku moodi küll, aga palju väiksem.
Sina, $arg, oled vist palju Bushi kõnesid kuulanud?
$arg: Mulle meeldib su lähenemine.  Nüüd näita, kuidas sa kaugened.
Sul, $arg, käis üks mõte peast läbi?  See pidi vast pikk ja üksildane teekond olema.
Kuule, $arg, mine õige Ameerika asepresidendiga pardijahile.
kas su vanemad tõesti vihkasid sind niipalju et $arg sulle nimeks panid või astusid enesevihkajate klubisse ja võtsid omale sellise nime ?:)
nimesid nimetamata aga $arg on ikka paras ajukääbik küll
Sa meeldid mulle $arg. Inimesed küll ütlevad, et mul ei ole maitset, aga sa meeldid mulle.
$arg: Ära hakka minuga plõksima. Nagunii sa jagu ei saa.
$arg: ära täna mind su solvamise eest. Seda oli nauding teha.
$arg: ära tunne ennast halvasti. Paljudel inimeste ei ole talenti.
$arg: ehk oled kunagi iluoperatsioonile mõelnud ?
$arg: Hei, sina! Kao mu planeedilt minema!
$arg: Hoiatus: mul on oma arvamus ja ma tean, kuidas seda kasutada.
$arg: Huvitav, miks tulnukad sulle pärakusse sondi jätsid?
$arg: Ideaalne aeg hakata kadunud inimeseks.
$arg: Ilus kleit. Loodad alla võtta, et sellesse ära mahtuda?
$arg: Ilus raseda kleit, sünnitad sa varsti?
$arg: ime kanni!
$arg: Inetusvõistlusel oleks sulle vääriliseks vastaseks ainlt üleeilne okseloik.
$arg: Jah, see on noku moodi küll, aga palju väiksem.
$arg: Ja milline seitsmest pöialpoisist sina oled?
$arg: ja mina mõtlesin maailma koledaim inimene küll siia ei juhtu...
$arg: käi jala.
$arg: kaos, paanika, korralagedus - sinu töö on siin edukalt tehtud.
$arg: kas ma mainisin, et kui sa mind puudutad, saad otsekohe jalaga munadesse?
$arg: kas sa käid ilusalongis tagavaraväljapääsu kaudu?
$arg: Kas su koduplaneedil keegi kunagi vait ka on?
$arg: Kas sulle tundub, et ma vajan seltskonda?
$arg: kui aju oleks vihm, siis sina oleks kõrb.
$arg: Kuidas ma saangi sinust puudust tunda, kui sa kunagi ära ei lähe?
$arg: Kuidas seda laserkaardikeppi taparežiimile lülitatakse
$arg: Kui inimest toiduga võrrelda, siis sina oled odav, maitsetu ja saad kiiresti valmis.
$arg: kui ma luban, et igatsen su järele, kas sa siis läheksid ära?
$arg: kui ma peaks tapma kõik kes sind vihkavad, siis see ei oleks mõrv...   ...see oleks genotsiid.
$arg: kui ma vajaks aju, siis ma võtaks sinu oma, sest seda ei ole kunagi kasutatud.
$arg: kui mu koeral oleks selline nägu nagu sul, siis ma raseeriks ta tagumiku ja õpetaks ta tagurpidi käima.
$arg: kui mul oleks vaja lonti saada, mõtleksin ma sinu peale
$arg: Küll sa näed ikka vahva välja. See kleit on sul pilapoest, eks?
$arg: kumb meist nüüd rohtu peaks võtma?
$arg: Kus on geenipolitsei? Siin on mingi mutant.
$arg: Kuuldavasti oli sul kunagi üks mõte, aga see suri üksinduse kätte ära.
$arg: ma annaks sulle ühe mõtte, aga ma ei ole kindel, kas sul on panna seda kuskile.
$arg: ma austan mulda, mis sind ootab.
$arg: Ma ei ole sinu tüüp. Ma pole täispuhutav.
$arg: ma ei tea mis sind nii lolliks teeb, aga see tõesti töötab.
$arg: Ma ei tea, mis viga sul küljes on, aga kindlasti on see raskesti hääldatava diagnoosiga.
$arg: ma ei unusta ühtegi nägu, aga sinu puhul tahaks küll erandi teha
$arg: Ma ei usu imesid. Ma arvestan nendega
$arg: ma küsiks kui vana sa oled, aga ma tean, et sa ei tunne nii suuri numbreid.
$arg: Ma kuulsin, et läksid ajuuuringutele, aga arstid ei leidnud sealt midagi.
$arg: mängime hobust. Mina olen esimene pool ja sina oled sina ise.
$arg: ma tõesti ei arva, et sa oled loll, aga mis minu arvamus loeb tuhandete teiste vastu.
$arg: ma tuleks meelsasti sinuga kohtama, aga mu lemmik reklaam on praegu telekas.
$arg: milline darwini auhind sulle kuulus ?
$arg, muidugi on ka sinul tunded. Aga keda see kotib?
$arg: mul on kiire praegu, võin ma sind mõni teine kord ignoreerida?
$arg: Naerata ja ütle: \"Jah, mu käskija.\"
$arg: Näri leiba!
$arg: nii-nii. Jälle on tsirkusest paar klouni putku pannud.
$arg: oled sa alati nii loll või pingutad täna eriti selle nimel?
$arg: oled sa TONT või Inimene ?
$arg: on need sinu silmamunad, mis ma oma dekolteest leidsin?
$arg: on see su nina või sööd sa banaani?
$arg: Parem ära mind vihasta. Mul hakkavad kirstud otsa saama
$arg: sa ei ole paranoik. Kõik vihkavad sind tõesti.
$arg: sa ei saa iialgi nii vanaks kui välja näed.
$arg: sa ei tea sõna \"hirm\" tähendust. Aga kui järele mõelda, siis sa ei tea enamuse sõnade tähendust.
$arg: sa oled loll kui leivaauto.
$arg: sa oled nii kole, et kui ma su loomaaeda viisin, siis talitaja ütles: \"Tänan, et ta tagasi tõite.\"
$arg, sul on nii inetu nägu, et see trükiti Ryanair oksekottidele.
$arg: sa oled nii kole, et su pilt trükiti Ryanair oksekottidele.
$arg: sa oled täpselt nagu Action Man: Kandiline soeng, armiline nägu ja püksis mitte midagi.
$arg: sa tõendad seda, et isegi jumal eksib vahest.
$arg: see, kui keegi sind ei mõista, ei tähenda veel, et sa oled kunstnik,
$arg: sind tehes läks Loojal vist küll vorm katki. Ja mõned nurgad jäid ilmselt maha kraapimata.
$arg: Sinuga dringile? Pigem teen endale ise tuimestuseta pimesooleoperatsiooni.
$arg: sinu lolliks nimetamine on solvang kõigile teistele lollidele.
$arg: sinu nõuannet ma küll ei vaja. Sa ei oska ju kahekümne ühenigi lugeda, kui sa alasti pole.
$arg, Sul on nii ilusad kõverad jalad
$arg: tavaliselt inimesed elavad ja õpivad. Sina ainult elad.
$arg: tunne end nagu kodus. Korista mu köök ja WC ära.
$arg: üldiselt ma ei taha küll kellegi kohta sitasti öelda aga sina oled ikka tõsiselt räige
$arg: võin ma sinult su nägu laenata, mu tagumik on puhkusel.
$arg: pane müts pähe.. rähn lendab
Kuule $arg, oled sa mingi Transport Object Assembler?
Võiks arvata, et $arg on mingi Konfiguratsioon.
$arg on topis nagu mingi java.
$arg: sinuga läheks luurele küll, aga tagasi tuleksin üksi
Ettevaatust: $arg võib pikaajalisel tarvitamisel pöördumatult kahjustada teie tervist
Mis on selle vaimuhaiguse nimi, mille põdeja tõi $arg ilmale?
Põrgusse see $arg, pigem närin endal pea otsast
$arg puhul on igasuguste teotuste väljamõtlemine mõttetu
$arg, häda on tulnud maale koos sinuga!
$arg: Kas sulle tundub, et ma vajan seltskonda?
Võrreldes $arg õudusega on Cthulhu nagu pehme kiisupoeg
Mis kuradi käkk see $arg sihuke on?
$arg meeldib mulle. Inimesed ütlevad, et mul puudub igasugune maitse, aga mulle ta meeldib.
rattaletõmbamise võiks asendada $arg kasutamisega
mullast on $arg tulnud ja mullaks peab ta ka saama
$arg: tahaks sulle vastu hambaid anda aga miks peaksin ma su välimust parandama?
$arg peal lasub vaaraode needus
peaga vastu seina peksmine on meeldivam kui $arg
$arg kui ohtlik psühholoogiline relv tuleks Genfi konventsiooniga keelustada
$arg: oled sa alati nii loll või on sul lihtsalt blond hetk?
$arg on nagu heroiin: korra proovid, igaveseks jama kaelas
$arg, siin on sulle Statoili kinkepakk, tarvita julgelt
$arg: kas sa oled alati nii loll või on täna mingi eriolukord?
ma ei tea, mis $arg nii lolliks teeb, aga igatahes see mõjub
$arg: mitu korda ma pean vett tõmbama, et sa ära kaoksid?
$arg, ükskord viid sa mu hauda!
$arg: ja mis on sinu olemasolu õigustus?
$arg on vajalik nagu ürask männile
$arg: sinu pilt on preservatiivipakkidel hoiatava näitena
$arg vanematest oli väga vastutustundetu keppida
$arg näeb pimedas palju parem välja
$arg: sina pede mine tagasi munni imema
$arg võiks oma vinnid ära pigistada enne mölisemist
$arg, kas sul tuld on? Siis pane end põlema.
isegi $arg psühhiaater keeldub teda kuulamast
$arg: ma ei mäleta su nime, luba ma kutsun sind perseussiks?
miks $arg mütsi perse peal kannab?
$arg on nii kole, et isegi kärbestel läheb süda pahaks
$arg on jälle eksinud nagu sõrm seedekulglasse
$arg ei saa kunagi nii kõvaks meheks kui ta ema oli
ma ei ole küll proktoloog, aga $arg ajud on pärasoolega vahetusse läinud
$arg: kondoom peas on tõepoolest sulle sobiv riietus!
$arg on vormis - ümmargune on ka vorm.
$arg: ema ütles sulle, et oled eriline, aga tegelikult oled sa lihtsalt loll
$arg on universumi loomulik hälve
$arg püstitas negatiivse IQ maailmarekordi
$arg on värske nagu munn saunas
$arg ei ole mitte homo vaid harilik pede
kui mul oleks Tourette sündroom, siis $arg põhjustaks hoogusid
$arg: näed seda kasti? Värsti näed ainult natuke vasaku silmaga seda. Seestpoolt.
$arg on nagu emo, kes on zileti kaotanud
$arg aju on evolutsiooni jäänuk
$arg: mine kümme meetrit eemale, sa solgid mu aura ära.
paistab, et $arg vanemad ei osanud lapsi teha
K: Mis on vahet $arg'l ja ämbritäiel sital? V: Ämber.
$arg: õpi oma vanemate vigadest - kasuta kondoomi.
ma oleks $arg isa, kui sada krooni poleks liiga palju olnud ta ema eest
$arg: mine varju - prügiauto tuleb
loodus oli $arg suhtes helde ainult 21. kromosoomi andes
$arg: ütle oma boyfriendile, et ta sulle rohkem suhu ei situks
kas kevad on juba, et $arg on lume alt välja sulanud?
kas keegi peeretas või ütles $arg midagi?
enamus inimesi moodustab sõnadest lauseid - kuid $arg on eriline
$arg: Sa käia oskad? Siis käi perse!
$arg vanemad kohtusid esimest korda suguvõsa kokkutulekul
see, et $arg jalge vahel midagi ripub ei tee temast veel meest
$arg: Kas sa põgenesid geneetikalaborist eile?
$arg: Sul on jälle päevad?
$arg: Palun mine katseklaasi tagasi!
see, et $arg ahvi moodi haiseb, ei tähenda veel, et ta oleks Tarzan
Vau! See pidi küll pirakas teerull olema, mis $arg näost üle sõitis.
$arg: säästa oma kopsumahtu tüdruku täis puhumiseks
ma ei suuda nii palju juua, et $arg inimest meenutama hakkaks
$arg on elav tõestus, et inimene saab elada ilma ajudeta.
ajud pole veel kõik - $arg korral pole nad mitte midagi
igasugune sarnasus $arg ja inimese vahel on täielik kokkusattumus
kui Frankenstein tahaks idiooti kokku panna, siis vajaks ta $arg tükke
kes jättis $arg puuri lahti?
$arg: ära tunne end halvasti - paljud inimesed on andetud
$arg: ära mõtle, sa võid oma ajud ära nikastada
$arg: palun räägi edasi, ehk ühel päeval ütled sa ka midagi tarka
Kui ma sööksin sada kilo nisukliisid, siis mu sitt oleks parem inimene kui $arg
$arg on kahjuks langenud anentsefaalia ohvriks
$arg: Su ema kepib telliste eest, et su õele litsimaja ehitada...
$arg on kole nagu hommikune Halonen
$arg: sul pole midagi sellist viga, mida reinkarnatsioon ei parandaks
$arg on tõestus, et jumalal on huumorimeel
$arg aju on samahästi kui uus, kuna seda pole kunagi kasutatud
tänu $arg jutu lugemisele on nüüd kõik siin kanalil lollimad...
Ma just kuulsin, et $arg on haige. Loodetavasti pole see midagi kerget.
$arg on tagasihoidlik inimene. Tal on põhjust selleks...
$arg: mulle tundub, et parim osa sinust jooksis mööda su ema persepragu alla ja lõppes pruuni plekina madratsil
Mõned toovad rõõmu igale poole, kus nad on. Ka $arg - lahkudes.
kui $arg auto alla jääb, siis ei ole see õnnetus.
Mind ei sega, et $arg räägib. Vähemalt niikaua kuni ma seda kuulama ei pea.
$arg tõestab, et ligi paari meetrine sitahunnik võib püsti püsida.
$arg: Sul on nägu mida ainult ema võiks armastada. Kuid ta vihkab sind...
$arg, külast just helistati. Nad tahavad oma lolli tagasi.
$arg: Ma ei elaks sinuga koos, isegi kui maailm oleks kusega üle ujutatud ja sa oleksid ainsa puu otsas.
$arg on alaväärsuskompleksiga - ja täiesti põhjendatult
$arg: Kas sa sündisid paksu limase sitajunnina, või pidid selleks saamiseks vaeva nägema?
$arg: Kas su vanematel on ka mõni elus laps?
$arg: Vastandid pidavat tõmbuma. Loodetavasti kohtud kellegi ilusa, targa ja kultuursega.
$arg: Sul on sitt arvamus inimestest kui arvad, et nad on sinuga võrdsed.
$arg on tugev nagu härg ja peaaegu sama intelligentne
$arg: Mul on hea meel, kui ütlesin sulle midagi mille pärast vabandama peaks :)
Taburet oleks $arg jaoks võrdväärne vestluspartner.
Ma ei tea mitu jalga on $arg-l, kuid taburetil on neid umbes samapalju.
Kui $arg kenam välja näeks, võiks ta töötada IT alal.
$arg: Tead, ma valan su munadeni betooni ja jätan suruõhuvasara kahe meetri kaugusele.
$arg, sina sinirohekollane tipitäpiline puust peaga ja plekist kõrvadega villastes sokkides lollaka naeratusega pilusilmne poolearuline ärakaranud vangi sarnane lampjalgne lasteaia lollpea, kas sa ei mäleta oma kohta?
$arg, tead sina, mine õige kasvata omale uus aju
$arg, palun loobu sellest liiva täis põlvikust, mida sa püksis kannad.
$arg: MIS SUL VIGA ON?
$arg: keri kolmikhüppega perse ja tõmba luuk ka tagant kinni
Kui taburet tagurpidi panna, siis saab $arg koos oma pedesõbraga istuda.
$arg kõlbab ainult litsimajja linu pesema
$arg: ebakõla sinu ja looduse vahel on sulle näkku kirjutatud
$arg: sina sitaviiul jää vait
$arg kuskil munni ei peaks imema?
$arg on nagu kaamel - küür seljas ja ila voolab
$arg: Miks sa minuga räägid? Ma pole puuetega laste hooldaja.
$arg: mängi endaga kusagil mujal.
$arg: tead, kui ma oleks sinu näoga, jookseks ma naerdes ketassae otsa
$arg: mine ära ja võta oma pokemon kaasa!
$arg: millal sa viimati ilma peeglit kasutamata oma munni nägid?
$arg: mängisid pipimängu jälle?
$arg: kaotasid küpsisemängus jälle?
$arg: miks sul häbe näos on?
$arg pärast ongi piimapakkidel kiri \"Ava siit\"
$arg on hea näide sellest, mis juhtub, kui õigel ajal aborti ei tehta
$arg on nii loll, et ei läbi isegi Turingi testi
$arg pea püsib ikka püsti - sooja õhku täis skalp ei kaalu ju palju ;)" | shuf -n1
