#!/bin/sh -e

regex='^!viktor\s*'

if [ -n "$CONFIG" ]
then
    echo "$regex"
    exit 0
fi

arg="$( echo "$@" | sed "s/$regex//I" )"

if [ -z "$arg" ]
then
    exit 1
fi

echo "Viktor Vassiljev: $arg olemine pole ainult amet, see on diagnoos elu lõpuni"
