#!/bin/sh -e

regex='^!(coop|konsum)\s*'

if [ -n "$CONFIG" ]
then
    echo "$regex"
    exit 1
fi

arg="$( echo "$@" | sed -r "s/$regex//I" )"

keyword="$( printf "%s" "$arg" | sed 's/\s/+/g' )"

json="$( curl -s "https://ecoop.ee/api/v1/products?ordering=relevancy&show_search=1&keyword=$keyword" )"

results="$( printf '%s' "$json" | jq -r '.results[] | "\(.sell_price) € \(.name)"' )"

count="$( printf '%s' "$json" | jq -r '.count' )"

if [ "$count" -eq 0 ]
then
    echo '?'
else
    echo "$results" | head -8

    if [ "$count" -gt 8 ]
    then
        printf "%s toodet: " "$count"
    fi

    echo "https://ecoop.ee/et/otsing/?ordering=relevancy&otsing=$keyword" \
        | sed 's/\s/+/g'
fi
