#!/bin/bash

if [ -n "$CONFIG" ]
then
    echo '^cpu$|^temp$|^temperature|celsius|^!?cputemp(!|\?)?$'
    exit 0
fi

# single Core
# CELSIUS=$(cat /sys/class/thermal/thermal_zone0/temp) && echo "scale=2; $CELSIUS/1000" | bc | tr "\n" " " && echo "Celsius"

# multi-core CPU
cat /sys/class/thermal/thermal_zone*/temp 2> /dev/null | while read p; do
  # echo "$p"
  CELSIUS="$p" && echo "scale=2; $CELSIUS/1000" | bc | tr "\n" " " && echo "Celsius"
done              
if [ "$(cat /sys/class/thermal/thermal_zone*/temp 2> /dev/null | wc -l)" == "0" ]; then
  echo "No CPU temperature information found."
fi
exit 0

# The __reply env variable set in the config file is not used in this script
#if [ -n "$__reply" ]
#then
#    echo "$__reply"
#else
#    echo 'P O N G'
#fi

# EOF
