#!/bin/sh
r="^\!decide\s"
if [ -n "$CONFIG" ]
then echo $r; exit
fi
a=$( echo $@ | sed "s/$r//" )
echo -n 'hmm... '
echo $a | egrep -q '(või|ja|or)'
if [ $? = 0 ]
then echo $a | sed -r 's/\s+(või|ja|or)\s+/\n/g'
else echo $a | sed -r 's/\s/\n/g'
fi | shuf -n1
