#!/bin/sh

regex="^\!decide\s"

if [ -n "$CONFIG" ]
then
    echo $regex
    exit
fi

args=$( echo $@ | sed "s/$regex//" )

echo -n 'hmm... '

echo $args | egrep -q '(või|ja|or)'

if [ $? = 0 ]
then
    echo $args | sed -r 's/\s+(või|ja|or)\s+/\n/g'
else
    echo $args | sed -r 's/\s/\n/g'
fi \
| shuf -n1
