#!/bin/sh

regex="^(\!ilm|ilm\?)"

if [ -n "$CONFIG" ]
then
    echo $regex
    exit
fi

dump=$( tempfile )

curl -s -o $dump https://kvlt.ee/ilm/

ilm='Tallinn Harku Tartu Võru Pärnu Brüssel'
last=$( echo $ilm | awk '{print $NF}' )

for city in $ilm
do
    temp=$( sed -nr "s/^$city-temp:\s(.+)$/\1/pi" $dump )
    [ -n "$temp" ] && echo -n "$city: $temp" | sed 's/\./,/g'
    [ "$city" = "$last" ] && echo || echo -n '; '
done

rm -f $dump
