#!/bin/sh

regex="^(\!ilm|ilm\?)"

if [ -n "$CONFIG" ]
then
    echo $regex
    exit
fi

tmp=$( tempfile )

curl -s -o $tmp https://kvlt.ee/ilm/

tln=$( sed -nr 's/^tallinn-temp:\s(.+)$/\1/p' $tmp )
hrk=$( sed -nr 's/^harku-temp:\s(.+)$/\1/p' $tmp )
prn=$( sed -nr 's/^pärnu-temp:\s(.+)$/\1/p' $tmp )
trt=$( sed -nr 's/^tartu-temp:\s(.+)$/\1/p' $tmp )
vru=$( sed -nr 's/^võru-temp:\s(.+)$/\1/p' $tmp )
bru=$( sed -nr 's/^brüssel-temp:\s(.+)$/\1/p' $tmp )

echo "Tallinn: $tln; Harku: $hrk; Pärnu: $prn; Tartu: $trt; Võru: $vru; Brüssel: $bru" | sed 's/\./,/g'

rm -f $tmp
