#!/bin/sh

regex='^(\!ilm|ilm\?)'

if [ -n "$CONFIG" ]
then
    echo "$regex"
    exit
fi

dump="$( tempfile )"

curl -s -o "$dump" https://kvlt.ee/ilm/

for city in Tallinn Harku Tartu Võru Pärnu Brüssel
do
    temp="$( sed -nr "s/^$city-temp:\s(.+)$/\1/pi" "$dump" )"
    [ -n "$temp" ] && echo "$city: $temp" | sed 's/\./,/g'
done

rm -f "$dump"
