#!/bin/sh -e

regex='^\!insult\s'

if [ -n "$CONFIG" ]
then
    echo "$regex"
    exit
fi

# https://github.com/mth/hirc/blob/master/insult.txt

insults=$( cat << EOF
$1: sa oled nuhtluseks maailmale loodud, et inimesed näeksid, kui madalale võib üks inimeseloom #linux.ee peal langeda.
$1: sa oled loll nagu lauajalg.
Tead $1, mine osta õige üks tükk seepi.
Erikuradikinomees sa $1 oled, reede õhta maatriksis!
$1: sa oled üks plekist persega vedruvasikas.
$1: käi jala.
$1, sa vana pede, sinu kohta on artikkel: http://www.$1.isgay.com/
$1: kalla end piimaga üle ja pane traktori kõrval põlema.
Oh püha perse kiriku laes, kuskohas küll $1'suguseid produtseeritakse.
$1: sina mine perse ja jäägi sinna.
$1: vabanda, kui ma sind kuidagi solvasin. See juhtus täiesti tahtlikult.
$1: ma ei saa aru, kuidas päike küll sinu peale paistes oksendama ei hakka.
$1: tra küll, kui mina sinu moodi välja näeks, ei julgeks ma ilma maskita väljagi minna
$1: ma ei näe su silmis mõistusehelki.
$1: kes küll sinusugusele ajukääbikule kirjakunsti õpetas?
$1: sina, sitavikat, ime kella!
$1: kas see on su nina, või kasvatad endale kolmandat kätt?
$1: mina olen blond, aga mis sinu vabandus on?
$1: kuidas Sulle kõrvaltvaatajana inimsugu tundub?
$1: sina ja inetu? Sa ei ole inetu, sa oled lihtsalt ... äh kuradile, Sa oled inetu. Sitaks inetu. Ja paks ka. Ja kiilakas.
$1: mitu korda ma pean vett tõmbama, et sa ära kaoksid?
$1: oled sa alati nii loll või on sul lihtsalt blond hetk??
K: Mida ütles jumal, kui ta $1' tegi? V: Oh shit!
K: Kui Empire State Building'u katuselt kukuvad alla paks neeger ja $1, siis kumb jõuab alla esimesena? V: Pole valge mehe asi.
K: Mis on $1' jaoks pikk ja raske? V: Algkool
$1 pole just karbi kõige kirkam kriit
$1: sa oled erakordselt sita väljanägemisega. On see mingi uus trend?
$1: kumb meist nüüd mürki peaks võtma?
$1: mõni küla on sinu pärast praegu ilma lollita.
$1: on see kitsehabe või on tuvid su lõua täis sittunud?
$1: palun seisa allatuult.
$1: sae pekki.
$1: Ah keri pekki
Kuule $1, sina kõdunenud kammeljas, sina mädanenud mudakukk, sina solgitud särg, mine osta omale õng.
$1: näri muru!
$1: kes sinusugusele kulendile suu andis?
$1: tead mis, PANE ENNAST PÕLEMA!
$1: söö sitta! (miljardid kärbsed ei saa ju ometi valel teel olla)
$1: sa näed välja nagu keedetud kaheksajalg
$1: sa oled meditsiiniline ime
$1: sa näed ikka vahva välja! See kleit su seljas on pilapoest, eks?
$1: kao eemale! Sa seisad mu aura peal!
$1 on mees, kes ei tee palju sõnu. Aga möliseb ikkagi rohkem kui vaja.
. o O ( Kus on geenipolitsei? Siin on mingi jälk $1 ) O o .
. o O ( Millise kivi alt küll sellised lontrused nagu $1 välja ronivad.. ) O o .
$1: kes ma Sinu arust olen? Kärbsepaber idiootidele?
$1: on Sul minut aega? Räägi mulle ära kõik, mida Sa üldse tead.
$1 on nii loll, et sobiks ideaalselt Võrno saatesse
$1: Su jutt kõlab nagu eesti keel, aga ma ei saa mitte halligi aru.
$1: kõik mu eelarvamused Sinu suhtes on ajapikku tõeks osutunud.
$1: ilmselgelt on ainuke lahendus sinu probleemile suitsiid.
$1: see et keegi sind ei mõista, ei tähenda veel et oled kunstnik.
$1 varub ilmselt alati spetsiaalselt aega, et end avalikus kohas lolliks teha.
$1: Kuuldavasti oli sul kunagi yks mõte, aga see suri yksinduse kätte ära.
$1: Ma vihkan kõiki. Sina oled järgmine.
$1: Ja sinu täiesti mõttetu arvamus on...?
$1: Pista pea perse ja tee porgandi häält.
$1: Kas sa nüüd taipad, mis juhtub kui sugulased omavahel abielluvad?
$1: Maakeral ei ole enam ruumi. Mine koju.
$1: Mine hoia oma pead vee all.
Isegi lollide maailmameistrivõistlustel saaks $1 teise koha, kuna ta on lihtsalt niivõrd loll....
$1: mine ära enne kui ma sind ümber lükkan.
Näe, tõmbasin küll vett, aga $1 ikka alla ei läinud.
Miskit rõvedat pininat tuleb kusagilt. Aaa, see oled sina, $1!
Tere $1! Kuidas viinaravi edeneb?
Vaene $1, kas sa jäid rongi alla või oledki sellisena sündinud?
$1: Piiblis on kirjas: "Juudas eemaldus ja läks ja poos end üles." Ja veel: "Mine tee sina samuti"
$1, miks sa ei lase oma mõistust teritada?
$1, tee mulle üks teene - ära unusta koduteel vales kohas tänavat ületada.
$1, mängime kodu, Sina oled uks ja mina löön su kinni.
$1, lähme kusagile, kus me saaksime teineteisest lahus olla.
Ma ei unusta kunagi ühtegi nägu, aga $1 puhul olen ma valmis erandi tegema.
$1, vaata, rong läheneb! Roni rööbastele!
$1, Sul on väga huvitav nägu, mitu korda Sind sinna löödud on?
$1, mängime hobust. Mina olen esimene ots ja sina võid lihtsalt iseennast mängida.
$1 nalju tervitab alati suur vaikusepahvak.
Ahv heitis $1'le ühe pilgu ning karjus: "Persse see Darwini teooria - mina endast inimest teha ei lase!"
Peab tunnistama, et $1'i sugused mehed ei kasva puu otsas - nad ripuvad okste küljes.
Kas tõesti on sõnade helge pea ja $1 vahel nii suur erinevus?
$1 on nagu lauaga löödud. Ja mitte ainult vastu rindu
Vaata $1't. Ilmne tõestus, et hullari aed on liiga madal.
Mõistuse pooles on $1'le kõige lähemal reha ... või äärmisel juhul labidas
$1, kas sa nüüd taipad, mis juhtub, kui sugulased omavahel abielluvad?
$1, ma suudan vaevu oma ükskõiksust vaos hoida
$1, sa tuled tuttav ette. Lahkasin sind vist zooloogiatunnis?
Kui mind huvitaks su arvamus, $1, siis ütleksin, milline see on.
Sinuga dringile, $1? Pigem teen endale ise tuimestuseta pimesooleoperatsiooni.
$1, kas sulle tundub, et ma vajan seltskonda?
Hei, sina, $1! Kao mu planeedilt minema!
$1, ja sinu tattnina-arvamus on...?
$1, ma ei ole tige. Olen lihtsalt juba 10 aastat väga halvas tujus.
$1, mis stiilis sa ka riietuda ei üritanud, välja see sul igastahes ei tulnud.
$1, kas su koduplaneedil keegi kunagi vait ka on?
Ma ei ole sinu tüüp, $1. Ma pole täispuhutav.
$1, kao eemale! Sa seisad mu aura peal.
$1: Ära muretse. Ma ei mäleta sinu nime ka.
$1, ma tahan lihtsalt kätte maksta. Mis selles halba on?
$1, kummarda ja ütle: "Jah, mu käskija."
$1, kas ma mainisin, et kui sa minuga räägid, saad kohe jalaga munadesse?
$1, sa näed erakordselt sitt välja. On see mingi uus trend?
$1, kumb meist nüüd rohtu peaks võtma?
$1: Kuidas seda laserkaardikeppi taparežiimile lülitatakse?
Ja milline seitsmest pöialpoisist sina, $1, oled?
$1: Ma sorisin küll kaltsupoes, aga seda hilpu ma seal küll ei näinud
Kus on geenipolitsei? Siin on mingi mutant, kes kasutab nime $1.
$1, küll sa näed ikka vahva välja. See kleit on sul pilapoest, eks?
$1, muidugi on ka meestel tunded. Aga keda see kotib?
Ilus kleit, $1. Loodad alla võtta, et sellesse ära mahtuda?
Parem ära mind vihasta $1. Mul hakkavad kirstud otsa saama
Oi, kui kena raseda kleit $1. Sa polegi? Nojah ...
Ma ei usu imesid, $1. Ma arvestan nendega
$1, räägi siis ometi! Sul on õigus oma lollile arvamusele.
Ma vihkan kõiki. Sina, $1, oled järgmine.
$1, Ja sinu täiesti mõttetu arvamus on...?
$1: Vaata ette - mul on oma arvamus ja ma tean, kuidas seda kasutada.
$1: Miks kipuvad kinniste peadega inimesed alati suu lahti tegema?
Ma olen andekas mitmel alal, $1. Suudan ühteaegu rääkida ja sinu peale laias kaarest kusta.
Ära hakka minuga plõksima, $1. Nagunii sa jagu ei saa.
Kuidas ma saangi sinust puudust tunda $1, kui sa kuidagi ära ei lähe?
$1: Stress kasvab üle pea, aga kägistada pole kedagi.
$1, sina oled üks hirmus õnnetus, mis headele inimestele kaela kukub.
$1, Sul on õigus vaikida. Kasuta seda ometi!
Kui inimest toiduga võrrelda, siis sina, $1, oled odav, maitsetu ja saad kiiresti valmis.
$1, kuuldavasti oli sul kunagi üks mõte, aga see suri üksinduse kätte ära.
$1, inetusvõistlusel oleks sulle vääriliseks vastaseks ainlt üleeilne okseloik.
$1: Ma olen nii õnnelik, et võiksin tappa.
$1, vabanda, kui tundus, et huvitad mind. Ei huvita.
$1, su tänane meik on küll puhas raiskamine.
$1, ma pole sinu tüüp. Mul on pulss.
$1, ma ei tea, mis viga sul küljes on, aga kindlasti on see raskesti hääldatava diagnoosiga.
$1, mida ma küll sinuta pihta hakkaksin? Peale selle, et oleksin õnnelik.
Palun räägi edasi, $1. Ma tahan magada.
$1, jah, see on noku moodi küll, aga palju väiksem.
Sina, $1, oled vist palju Bushi kõnesid kuulanud?
$1: Mulle meeldib su lähenemine.  Nüüd näita, kuidas sa kaugened.
Sul, $1, käis üks mõte peast läbi?  See pidi vast pikk ja üksildane teekond olema.
Kuule, $1, mine õige Ameerika asepresidendiga pardijahile.
kas su vanemad tõesti vihkasid sind niipalju et $1 sulle nimeks panid või astusid enesevihkajate klubisse ja võtsid omale sellise nime ?:)
nimesid nimetamata aga $1 on ikka paras ajukääbik küll
Sa meeldid mulle $1. Inimesed küll ütlevad, et mul ei ole maitset, aga sa meeldid mulle.
$1: Ära hakka minuga plõksima. Nagunii sa jagu ei saa.
$1: ära täna mind su solvamise eest. Seda oli nauding teha.
$1: ära tunne ennast halvasti. Paljudel inimeste ei ole talenti.
$1: ehk oled kunagi iluoperatsioonile mõelnud ?
$1: Hei, sina! Kao mu planeedilt minema!
$1: Hoiatus: mul on oma arvamus ja ma tean, kuidas seda kasutada.
$1: Huvitav, miks tulnukad sulle pärakusse sondi jätsid?
$1: Ideaalne aeg hakata kadunud inimeseks.
$1: Ilus kleit. Loodad alla võtta, et sellesse ära mahtuda?
$1: Ilus raseda kleit, sünnitad sa varsti?
$1: ime kanni!
$1: Inetusvõistlusel oleks sulle vääriliseks vastaseks ainlt üleeilne okseloik.
$1: Jah, see on noku moodi küll, aga palju väiksem.
$1: Ja milline seitsmest pöialpoisist sina oled?
$1: ja mina mõtlesin maailma koledaim inimene küll siia ei juhtu...
$1: käi jala.
$1: kaos, paanika, korralagedus - sinu töö on siin edukalt tehtud.
$1: kas ma mainisin, et kui sa mind puudutad, saad otsekohe jalaga munadesse?
$1: kas sa käid ilusalongis tagavaraväljapääsu kaudu?
$1: Kas su koduplaneedil keegi kunagi vait ka on?
$1: Kas sulle tundub, et ma vajan seltskonda?
$1: kui aju oleks vihm, siis sina oleks kõrb.
$1: Kuidas ma saangi sinust puudust tunda, kui sa kunagi ära ei lähe?
$1: Kuidas seda laserkaardikeppi taparežiimile lülitatakse
$1: Kui inimest toiduga võrrelda, siis sina oled odav, maitsetu ja saad kiiresti valmis.
$1: kui ma luban, et igatsen su järele, kas sa siis läheksid ära?
$1: kui ma peaks tapma kõik kes sind vihkavad, siis see ei oleks mõrv...   ...see oleks genotsiid.
$1: kui ma vajaks aju, siis ma võtaks sinu oma, sest seda ei ole kunagi kasutatud.
$1: kui mu koeral oleks selline nägu nagu sul, siis ma raseeriks ta tagumiku ja õpetaks ta tagurpidi käima.
$1: kui mul oleks vaja lonti saada, mõtleksin ma sinu peale
$1: Küll sa näed ikka vahva välja. See kleit on sul pilapoest, eks?
$1: kumb meist nüüd rohtu peaks võtma?
$1: Kus on geenipolitsei? Siin on mingi mutant.
$1: Kuuldavasti oli sul kunagi üks mõte, aga see suri üksinduse kätte ära.
$1: ma annaks sulle ühe mõtte, aga ma ei ole kindel, kas sul on panna seda kuskile.
$1: ma austan mulda, mis sind ootab.
$1: Ma ei ole sinu tüüp. Ma pole täispuhutav.
$1: ma ei tea mis sind nii lolliks teeb, aga see tõesti töötab.
$1: Ma ei tea, mis viga sul küljes on, aga kindlasti on see raskesti hääldatava diagnoosiga.
$1: ma ei unusta ühtegi nägu, aga sinu puhul tahaks küll erandi teha
$1: Ma ei usu imesid. Ma arvestan nendega
$1: ma küsiks kui vana sa oled, aga ma tean, et sa ei tunne nii suuri numbreid.
$1: Ma kuulsin, et läksid ajuuuringutele, aga arstid ei leidnud sealt midagi.
$1: mängime hobust. Mina olen esimene pool ja sina oled sina ise.
$1: ma tõesti ei arva, et sa oled loll, aga mis minu arvamus loeb tuhandete teiste vastu.
$1: ma tuleks meelsasti sinuga kohtama, aga mu lemmik reklaam on praegu telekas.
$1: milline darwini auhind sulle kuulus ?
$1, muidugi on ka sinul tunded. Aga keda see kotib?
$1: mul on kiire praegu, võin ma sind mõni teine kord ignoreerida?
$1: Naerata ja ütle: "Jah, mu käskija."
$1: Näri leiba!
$1: nii-nii. Jälle on tsirkusest paar klouni putku pannud.
$1: oled sa alati nii loll või pingutad täna eriti selle nimel?
$1: oled sa TONT või Inimene ?
$1: on need sinu silmamunad, mis ma oma dekolteest leidsin?
$1: on see su nina või sööd sa banaani?
$1: Parem ära mind vihasta. Mul hakkavad kirstud otsa saama
$1: sa ei ole paranoik. Kõik vihkavad sind tõesti.
$1: sa ei saa iialgi nii vanaks kui välja näed.
$1: sa ei tea sõna "hirm" tähendust. Aga kui järele mõelda, siis sa ei tea enamuse sõnade tähendust.
$1: sa oled loll kui leivaauto.
$1: sa oled nii kole, et kui ma su loomaaeda viisin, siis talitaja ütles: "Tänan, et ta tagasi tõite."
$1, sul on nii inetu nägu, et see trükiti Ryanair oksekottidele.
$1: sa oled nii kole, et su pilt trükiti Ryanair oksekottidele.
$1: sa oled täpselt nagu Action Man: Kandiline soeng, armiline nägu ja püksis mitte midagi.
$1: sa tõendad seda, et isegi jumal eksib vahest.
$1: see, kui keegi sind ei mõista, ei tähenda veel, et sa oled kunstnik,
$1: sind tehes läks Loojal vist küll vorm katki. Ja mõned nurgad jäid ilmselt maha kraapimata.
$1: Sinuga dringile? Pigem teen endale ise tuimestuseta pimesooleoperatsiooni.
$1: sinu lolliks nimetamine on solvang kõigile teistele lollidele.
$1: sinu nõuannet ma küll ei vaja. Sa ei oska ju kahekümne ühenigi lugeda, kui sa alasti pole.
$1, Sul on nii ilusad kõverad jalad
$1: tavaliselt inimesed elavad ja õpivad. Sina ainult elad.
$1: tunne end nagu kodus. Korista mu köök ja WC ära.
$1: üldiselt ma ei taha küll kellegi kohta sitasti öelda aga sina oled ikka tõsiselt räige
$1: võin ma sinult su nägu laenata, mu tagumik on puhkusel.
$1: pane müts pähe.. rähn lendab
Kuule $1, oled sa mingi Transport Object Assembler?
Võiks arvata, et $1 on mingi Konfiguratsioon.
$1 on topis nagu mingi java.
$1: sinuga läheks luurele küll, aga tagasi tuleksin üksi
Ettevaatust: $1 võib pikaajalisel tarvitamisel pöördumatult kahjustada teie tervist
Mis on selle vaimuhaiguse nimi, mille põdeja tõi $1 ilmale?
Põrgusse see $1, pigem närin endal pea otsast
$1 puhul on igasuguste teotuste väljamõtlemine mõttetu
$1, häda on tulnud maale koos sinuga!
$1: Kas sulle tundub, et ma vajan seltskonda?
Võrreldes $1 õudusega on Cthulhu nagu pehme kiisupoeg
Mis kuradi käkk see $1 sihuke on?
$1 meeldib mulle. Inimesed ütlevad, et mul puudub igasugune maitse, aga mulle ta meeldib.
rattaletõmbamise võiks asendada $1 kasutamisega
mullast on $1 tulnud ja mullaks peab ta ka saama
$1: tahaks sulle vastu hambaid anda aga miks peaksin ma su välimust parandama?
$1 peal lasub vaaraode needus
peaga vastu seina peksmine on meeldivam kui $1
$1 kui ohtlik psühholoogiline relv tuleks Genfi konventsiooniga keelustada
$1: oled sa alati nii loll või on sul lihtsalt blond hetk?
$1 on nagu heroiin: korra proovid, igaveseks jama kaelas
$1, siin on sulle Statoili kinkepakk, tarvita julgelt
$1: kas sa oled alati nii loll või on täna mingi eriolukord?
ma ei tea, mis $1 nii lolliks teeb, aga igatahes see mõjub
$1: mitu korda ma pean vett tõmbama, et sa ära kaoksid?
$1, ükskord viid sa mu hauda!
$1: ja mis on sinu olemasolu õigustus?
$1 on vajalik nagu ürask männile
$1: sinu pilt on preservatiivipakkidel hoiatava näitena
$1 vanematest oli väga vastutustundetu keppida
$1 näeb pimedas palju parem välja
$1: sina pede mine tagasi munni imema
$1 võiks oma vinnid ära pigistada enne mölisemist
$1, kas sul tuld on? Siis pane end põlema.
isegi $1 psühhiaater keeldub teda kuulamast
$1: ma ei mäleta su nime, luba ma kutsun sind perseussiks?
miks $1 mütsi perse peal kannab?
$1 on nii kole, et isegi kärbestel läheb süda pahaks
$1 on jälle eksinud nagu sõrm seedekulglasse
$1 ei saa kunagi nii kõvaks meheks kui ta ema oli
ma ei ole küll proktoloog, aga $1 ajud on pärasoolega vahetusse läinud
$1: kondoom peas on tõepoolest sulle sobiv riietus!
$1 on vormis - ümmargune on ka vorm.
$1: ema ütles sulle, et oled eriline, aga tegelikult oled sa lihtsalt loll
$1 on universumi loomulik hälve
$1 püstitas negatiivse IQ maailmarekordi
$1 on värske nagu munn saunas
$1 ei ole mitte homo vaid harilik pede
kui mul oleks Tourette sündroom, siis $1 põhjustaks hoogusid
$1: näed seda kasti? Värsti näed ainult natuke vasaku silmaga seda. Seestpoolt.
$1 on nagu emo, kes on zileti kaotanud
$1 aju on evolutsiooni jäänuk
$1: mine kümme meetrit eemale, sa solgid mu aura ära.
paistab, et $1 vanemad ei osanud lapsi teha
K: Mis on vahet $1'l ja ämbritäiel sital? V: Ämber.
$1: õpi oma vanemate vigadest - kasuta kondoomi.
ma oleks $1 isa, kui sada krooni poleks liiga palju olnud ta ema eest
$1: mine varju - prügiauto tuleb
loodus oli $1 suhtes helde ainult 21. kromosoomi andes
$1: ütle oma boyfriendile, et ta sulle rohkem suhu ei situks
kas kevad on juba, et $1 on lume alt välja sulanud?
kas keegi peeretas või ütles $1 midagi?
enamus inimesi moodustab sõnadest lauseid - kuid $1 on eriline
$1: Sa käia oskad? Siis käi perse!
$1 vanemad kohtusid esimest korda suguvõsa kokkutulekul
see, et $1 jalge vahel midagi ripub ei tee temast veel meest
$1: Kas sa põgenesid geneetikalaborist eile?
$1: Sul on jälle päevad?
$1: Palun mine katseklaasi tagasi!
see, et $1 ahvi moodi haiseb, ei tähenda veel, et ta oleks Tarzan
Vau! See pidi küll pirakas teerull olema, mis $1 näost üle sõitis.
$1: säästa oma kopsumahtu tüdruku täis puhumiseks
ma ei suuda nii palju juua, et $1 inimest meenutama hakkaks
$1 on elav tõestus, et inimene saab elada ilma ajudeta.
ajud pole veel kõik - $1 korral pole nad mitte midagi
igasugune sarnasus $1 ja inimese vahel on täielik kokkusattumus
kui Frankenstein tahaks idiooti kokku panna, siis vajaks ta $1 tükke
kes jättis $1 puuri lahti?
$1: ära tunne end halvasti - paljud inimesed on andetud
$1: ära mõtle, sa võid oma ajud ära nikastada
$1: palun räägi edasi, ehk ühel päeval ütled sa ka midagi tarka
Kui ma sööksin sada kilo nisukliisid, siis mu sitt oleks parem inimene kui $1
$1 on kahjuks langenud anentsefaalia ohvriks
$1: Su ema kepib telliste eest, et su õele litsimaja ehitada...
$1 on kole nagu hommikune Halonen
$1: sul pole midagi sellist viga, mida reinkarnatsioon ei parandaks
$1 on tõestus, et jumalal on huumorimeel
$1 aju on samahästi kui uus, kuna seda pole kunagi kasutatud
tänu $1 jutu lugemisele on nüüd kõik siin kanalil lollimad...
Ma just kuulsin, et $1 on haige. Loodetavasti pole see midagi kerget.
$1 on tagasihoidlik inimene. Tal on põhjust selleks...
$1: mulle tundub, et parim osa sinust jooksis mööda su ema persepragu alla ja lõppes pruuni plekina madratsil
Mõned toovad rõõmu igale poole, kus nad on. Ka $1 - lahkudes.
kui $1 auto alla jääb, siis ei ole see õnnetus.
Mind ei sega, et $1 räägib. Vähemalt niikaua kuni ma seda kuulama ei pea.
$1 tõestab, et ligi paari meetrine sitahunnik võib püsti püsida.
$1: Sul on nägu mida ainult ema võiks armastada. Kuid ta vihkab sind...
$1, külast just helistati. Nad tahavad oma lolli tagasi.
$1: Ma ei elaks sinuga koos, isegi kui maailm oleks kusega üle ujutatud ja sa oleksid ainsa puu otsas.
$1 on alaväärsuskompleksiga - ja täiesti põhjendatult
$1: Kas sa sündisid paksu limase sitajunnina, või pidid selleks saamiseks vaeva nägema?
$1: Kas su vanematel on ka mõni elus laps?
$1: Vastandid pidavat tõmbuma. Loodetavasti kohtud kellegi ilusa, targa ja kultuursega.
$1: Sul on sitt arvamus inimestest kui arvad, et nad on sinuga võrdsed.
$1 on tugev nagu härg ja peaaegu sama intelligentne
$1: Mul on hea meel, kui ütlesin sulle midagi mille pärast vabandama peaks :)
Taburet oleks $1 jaoks võrdväärne vestluspartner.
Ma ei tea mitu jalga on $1-l, kuid taburetil on neid umbes samapalju.
Kui $1 kenam välja näeks, võiks ta töötada IT alal.
$1: Tead, ma valan su munadeni betooni ja jätan suruõhuvasara kahe meetri kaugusele.
$1, sina sinirohekollane tipitäpiline puust peaga ja plekist kõrvadega villastes sokkides lollaka naeratusega pilusilmne poolearuline ärakaranud vangi sarnane lampjalgne lasteaia lollpea, kas sa ei mäleta oma kohta?
$1, tead sina, mine õige kasvata omale uus aju
$1, palun loobu sellest liiva täis põlvikust, mida sa püksis kannad.
$1: MIS SUL VIGA ON?
$1: keri kolmikhüppega perse ja tõmba luuk ka tagant kinni
Kui taburet tagurpidi panna, siis saab $1 koos oma pedesõbraga istuda.
$1 kõlbab ainult litsimajja linu pesema
$1: ebakõla sinu ja looduse vahel on sulle näkku kirjutatud
$1: sina sitaviiul jää vait
$1 kuskil munni ei peaks imema?
$1 on nagu kaamel - küür seljas ja ila voolab
$1: Miks sa minuga räägid? Ma pole puuetega laste hooldaja.
$1: mängi endaga kusagil mujal.
$1: tead, kui ma oleks sinu näoga, jookseks ma naerdes ketassae otsa
$1: mine ära ja võta oma pokemon kaasa!
$1: millal sa viimati ilma peeglit kasutamata oma munni nägid?
$1: mängisid pipimängu jälle?
$1: kaotasid küpsisemängus jälle?
$1: miks sul häbe näos on?
$1 pärast ongi piimapakkidel kiri "Ava siit"
$1 on hea näide sellest, mis juhtub, kui õigel ajal aborti ei tehta
$1 on nii loll, et ei läbi isegi Turingi testi
$1 pea püsib ikka püsti - sooja õhku täis skalp ei kaalu ju palju ;)
EOF
)

args="$( echo "$@" | sed "s/$regex//I" )"

echo "$insults" | shuf -n1 | sed -e "s/\$1/$args/g"
