#!/bin/sh

# https://github.com/mth/hirc/blob/master/insult.txt

regex='^\!insult\s'

if [ -n "$CONFIG" ]
then
    echo "$regex"
    exit
fi

args="$( echo "$@" | sed "s/$regex//I" )"

shuf -n1 insult.txt | sed -e "s/\$1/$args/g"
