#!/bin/sh -e

if [ -n "$CONFIG" ]
then
    echo '^!?koroona\??$'
    exit 0
fi

__get() {
    c=/tmp/koroona-cache
    [ -f "$c" ] && a=$(( $( date +%s ) - $( date -r "$c" +%s ) ))
    if [ ! -f "$c" ] || [ "$a" -gt 500 ]
    then curl -s -A tiny-matrix-bot -o "$c" "$1"
    fi
    cat "$c"
}

d="$( __get 'https://et.wikipedia.org/w/index.php?title=2020._aasta_koroonaviirushaiguse_pandeemia_Eestis&action=raw' )"
n="$( echo "$d" | sed -nr 's/.*nakatunuid\s*=\s*([0-9]+).*/\1/p' )"

echo "$n nakatunut"
