#!/bin/sh -e

if [ -n "$CONFIG" ]
then
    echo '^!?koroona\??$'
    exit 0
fi

__get() {
    c=/tmp/koroona-terviseamet-cache
    [ -f "$c" ] && a=$(( $( date +%s ) - $( date -r "$c" +%s ) ))
    if [ ! -f "$c" ] || [ "$a" -gt 500 ]
    then curl -s -A tiny-matrix-bot -o "$c" "$1"
    fi
    cat "$c"
}

d="$( __get https://www.terviseamet.ee/et/uuskoroonaviirus \
    | sed -nr 's/.+(Terviseamet on kokku.+osutunud positiivseks\.).+/\1/p' \
    | grep -Eo '[0-9]+' )"

t="$( echo "$d" | head -1 )"
p="$( echo "$d" | tail -1 )"

echo "Terviseamet on kokku analüüsinud $t proovi, millest $p on osutunud positiivseks."
