#!/bin/bash

if [ -n "$CONFIG" ]; then
        echo '^mn$|^mn .*$'
        exit 0
fi

TORIFY="torify"

# tor and torify should be installed for your privacy.
type torify >/dev/null 2>&1 || {
        echo "It is recommended that you install the packge \"tor\" on the server for privacy."
        TORIFY=""
}

arg1=$(echo "$1" | tr -s ' ' | cut -s -d ' ' -f 2)
#echo "mn: argument 1: \"$arg1\""
if [ "$arg1" == "" ]; then
        arg1=1 # default value if none given by user
fi
case "$arg1" in
'' | *[!0-9]*)
        echo "First argument is not a number. Skipping. Try \"mn\" or \"mn 2\"."
        exit 0
        ;;
*)
        # echo "First argument is a number. "
        ;;
esac

case "$arg1" in
'' | 1)
        $TORIFY curl --silent --compressed "https://data.messari.io/api/v1/news" | jq '.data[1] | .url, .title , .content ' 2>>/dev/null
        ;;
2)
        $TORIFY curl --silent --compressed "https://data.messari.io/api/v1/news" | jq '.data[1,2] | .url, .title , .content ' | sed '0~3 s/$/\n\n/g' 2>>/dev/null
        ;;
3)
        $TORIFY curl --silent --compressed "https://data.messari.io/api/v1/news" | jq '.data[1,2,3] | .url, .title , .content ' | sed '0~3 s/$/\n\n/g' 2>>/dev/null
        ;;
4)
        $TORIFY curl --silent --compressed "https://data.messari.io/api/v1/news" | jq '.data[1,2,3,4] | .url, .title , .content ' | sed '0~3 s/$/\n\n/g' 2>>/dev/null
        ;;
5)
        $TORIFY curl --silent --compressed "https://data.messari.io/api/v1/news" | jq '.data[1,2,3,4,5] | .url, .title , .content ' | sed '0~3 s/$/\n\n/g' 2>>/dev/null
        ;;
6)
        $TORIFY curl --silent --compressed "https://data.messari.io/api/v1/news" | jq '.data[1,2,3,4,5,6] | .url, .title , .content ' | sed '0~3 s/$/\n\n/g' 2>>/dev/null
        ;;
7)
        $TORIFY curl --silent --compressed "https://data.messari.io/api/v1/news" | jq '.data[1,2,3,4,5,6,7] | .url, .title , .content ' | sed '0~3 s/$/\n\n/g' 2>>/dev/null
        ;;
8)
        $TORIFY curl --silent --compressed "https://data.messari.io/api/v1/news" | jq '.data[1,2,3,4,5,6,7,8] | .url, .title , .content ' | sed '0~3 s/$/\n\n/g' 2>>/dev/null
        ;;
9)
        $TORIFY curl --silent --compressed "https://data.messari.io/api/v1/news" | jq '.data[1,2,3,4,5,6,7,8,9] | .url, .title , .content ' | sed '0~3 s/$/\n\n/g' 2>>/dev/null
        ;;
10)
        $TORIFY curl --silent --compressed "https://data.messari.io/api/v1/news" | jq '.data[1,2,3,4,5,6,7,8,9,10] | .url, .title , .content ' | sed '0~3 s/$/\n\n/g' 2>>/dev/null
        ;;
11)
        $TORIFY curl --silent --compressed "https://data.messari.io/api/v1/news" | jq '.data[1,2,3,4,5,6,7,8,9,10,11] | .url, .title , .content ' | sed '0~3 s/$/\n\n/g' 2>>/dev/null
        ;;
12)
        $TORIFY curl --silent --compressed "https://data.messari.io/api/v1/news" | jq '.data[1,2,3,4,5,6,7,8,9,10,11,12] | .url, .title , .content ' | sed '0~3 s/$/\n\n/g' 2>>/dev/null
        ;;
13)
        $TORIFY curl --silent --compressed "https://data.messari.io/api/v1/news" | jq '.data[1,2,3,4,5,6,7,8,9,10,11,12,13] | .url, .title , .content ' | sed '0~3 s/$/\n\n/g' 2>>/dev/null
        ;;
14)
        $TORIFY curl --silent --compressed "https://data.messari.io/api/v1/news" | jq '.data[1,2,3,4,5,6,7,8,9,10,11,12,13,14] | .url, .title , .content ' | sed '0~3 s/$/\n\n/g' 2>>/dev/null
        ;;
15)
        $TORIFY curl --silent --compressed "https://data.messari.io/api/v1/news" | jq '.data[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15] | .url, .title , .content ' | sed '0~3 s/$/\n\n/g' 2>>/dev/null
        ;;
*)
        echo "You want too many or you want something foolish. I will give you 1 news article"
        $TORIFY curl --silent --compressed "https://data.messari.io/api/v1/news" | jq '.data[1] | .url, .title , .content ' 2>>/dev/null
        ;;
esac

#if [ -n "$__reply" ]
#then
#    echo "$__reply"
#else
#    echo 'P O N G'
#fi
