#!/bin/sh -e

regex='^!(otsusta|vali)\s*'

if [ -n "$CONFIG" ]
then
    echo "$regex"
    exit 0
fi

s="$( echo "$@" | sed -r "s/$regex//I" )"

[ -z "$s" ] && exit 1

echo 'hmm...'
echo
echo "$s" | sed -r 's/(\s+või\s+)/\n/gI' | shuf -n1
