#!/bin/sh -e

if [ -n "$CONFIG" ]
then
    echo '^!?päike\??$'
    exit 0
fi

_()
{
    o="$( hdate -q -s -l "N$1" -L "E$2" -z "$( date +%z | sed 's/[+0]//g' )" )"
    r="$( echo "$o" | grep -Po '(?<=sunrise:\s).+' )"
    s="$( echo "$o" | grep -Po '(?<=sunset:\s).+' )"
    if [ "$( date -d "$r" +%s )" -gt "$( date +%s )" ]
    then echo "🌅 $r $3"
    else echo "🌇 $s $3"
    fi
}

_ 59.437222 24.745278 Tallinn
_ 58.383333 26.716667 Tartu
_ 58.383333 24.500000 Pärnu
_ 57.848611 26.992778 Võru
_ 58.224444 26.421111 Elva
