#!/bin/sh

# https://github.com/mth/hirc/blob/master/plans.txt

regex="^\!plan\s"

if [ -n "$CONFIG" ]
then
    echo $regex
    exit
fi

args=$( echo $@ | sed "s/$regex//" )

echo "1. $args"
echo "2. ???"
echo "3. $( shuf -n1 plan.txt )"
