#!/bin/sh -e

if [ -n "$CONFIG" ]; then
        echo '^!?pong(!|\?)?$'
        exit 0
fi

# shellcheck disable=SC2154
if [ -n "$__reply" ]; then
        echo "$__reply"
else
        echo 'P I N G'
fi
