#!/bin/bash

if [ -n "$CONFIG" ]; then
        echo '^top$|^top .*$'
        exit 0
fi

echo "Top 5 CPU consumers:"
#ps -eo %cpu,pid,ppid,cmd --sort=-%cpu | head
ps -eo %cpu,cmd --sort=-%cpu --cols 40 | head -n 5
echo ""
echo "Top 5 RAM consumers:"
#ps -eo %mem,pid,ppid,cmd --sort=-%mem | head
ps -eo %mem,cmd --sort=-%mem --cols 40 | head -n 5

#if [ -n "$__reply" ]
#then
#    echo "$__reply"
#else
#    echo 'P O N G'
#fi
