#!/bin/sh -e

regex='^!vali\s'

if [ -n "$CONFIG" ]
then
    echo "$regex"
    exit
fi

args="$( echo "$@" | sed "s/$regex//I" )"

echo 'hmm...'
echo

if echo "$args" | grep -Eiq '(või|ja)'
then
    echo "$args" | sed -r 's/\s+(või|ja)\s+/\n/gI'
else
    echo "$args" | sed -r 's/\s/\n/gI'
fi \
| shuf -n1
