#!/bin/sh -e

regex='^!viktor\s'

if [ -n "$CONFIG" ]
then
    echo "$regex"
    exit 0
fi

n="$( echo "$@" | sed "s/$regex//I" )"

[ -z "$n" ] && exit 1

echo "Viktor Vassiljev: $n olemine pole ainult amet, see on diagnoos elu lõpuni"
