#!/bin/bash

if [ -n "$CONFIG" ]; then
        echo 'www|web|^!?web .*$|^!?www .*$|^browse$|^browse .*$'
        exit 0
fi

TORIFY="torify"

# tor and torify should be installed for your privacy.
type torify >/dev/null 2>&1 || {
        echo "It is recommended that you install the packge \"tor\" on the server for privacy."
        TORIFY=""
}

# w3m must be installed
type w3m >/dev/null 2>&1 || {
        echo "This script requires that you install the packge \"w3m\" on the server."
        exit 0
}

args=$(echo "$1" | tr -s ' ' | cut -s -d ' ' -f 2-)
#echo "web: arguments: \"$args\""
if [ "$args" == "" ]; then
        echo "You must be browsing some URL. Try \"web news.ycombinator.com\"."
        # echo "If torify is available all traffic will go through TOR by default."
        # echo "If you really must skip TOR, try \"web notorify news.ycombinator.com\"."
        exit 0
fi

arg1=$(echo "$args" | tr -s ' ' | cut -s -d ' ' -f 1)
if [ "$arg1" == "notorify" ]; then
        TORIFY=""
        args=$(echo "$args" | tr -s ' ' | cut -s -d ' ' -f 2-) # remove first arg
fi
$TORIFY w3m -dump "$args"

# Argument __reply from config file is not used in this script
#if [ -n "$__reply" ]
#then
#    echo "$__reply"
#else
#    echo 'P O N G'
#fi
